[package]
name = "rust-study"
version = "0.1.0"
edition = "2021"
publish = ["artifactory"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
itertools = "0.10.3"
maplit = "1.0.2"
